Adds a parameter for the timestamp server url
DanaBear/code-sign-action pull request #2
Opened 2021-02-08 20:50 UTC by dougbradbury

I was having trouble with the default timeserver and wanted to be able
to use others. Particularly, the server that the vendor of my cert
recommends.

Also adds missing parameters to action.yml

2021-06-14 16:14 UTC, fbaptista commented
We created simmilar WA for this. +1 to the PR

2021-07-05 10:15 UTC, MurrayGroves approved these changes
Also have the same problem. This seems like a good solution.

2021-07-05 10:51 UTC, MurrayGroves requested changes
The changes should be in `dist/index.js` not `index.ts`, since that's what `action.yml` runs. Changes in `index.ts` don't seem to do anything and I'm not sure of the file's purpose.

2021-07-23 08:11 UTC, overheadhunter reviewed
The action.yml supports default values in machine-readable format as well.

2021-07-23 08:11 UTC, overheadhunter commented on action.yml
> +    required: false
```suggestion
    required: false
    default: 'http://timestamp.verisign.com/scripts/timstamp.dll'
```

2021-07-23 08:14 UTC, overheadhunter commented
@Dana-Prajea This PR is open for a while now, do you plan to improve your awesome GH Action further? There are plenty forks already, but I'm a fan of merging changes back to the original project to avoid fragmentation.

2021-07-23 08:17 UTC, overheadhunter commented
> The changes should be in `dist/index.js` not `index.ts`, since that's what `action.yml` runs. Changes in `index.ts` don't seem to do anything and I'm not sure of the file's purpose.

.ts will get transpiled to .js

2021-08-17 12:58 UTC, krzysztofsitnik approved these changes

2021-08-17 13:00 UTC, krzysztofsitnik commented
Can you please merge it?

2021-08-17 20:59 UTC, merged